# Generated by Django 2.1.4 on 2019-04-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=16, unique=True)),
                ('pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
