# Generated by Django 2.1.4 on 2019-05-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
